title: New Course 3
description: Course 3 description.
template:
  repo: new-course-3-template
  name: new-course-3
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
